// lib/products.ts
// M'ÉTERNELLE — Ürün Kataloğu (32 ürün, Excel'den)
// Shopify entegrasyonu hazır olunca bu dosya kaldırılacak.

export type Product = {
  id: string
  slug: string
  code: string
  name: string
  description: string
  price: number
  desen: 'PAV' | 'VAS' | 'VİRİDİS' | 'ROSEA' | 'MONOGRAM'
  pattern: string
  category: 'kimono' | 'gomlek' | 'kaftan' | 'bluz' | 'atlet' | 'sort' | 'pantolon' | 'elbise'
  beden: string[]
  image: string
  images: string[]
  in_stock: boolean
}

const BASE = '/images/products/M_Éternelle Çekimler 161024'
const p = (num: string) => `${BASE}/Méternelle Çekim${num}-Edit.jpg`
const p2 = (num: string) => `${BASE}/Méternelle Çekim${num}-Edit-2.jpg`

export const products: Product[] = [

  // ═══════════════════════════════════════
  // PAV — 7 ürün
  // ═══════════════════════════════════════

  {
    id: 'pav-td-ok',
    slug: 'pav-kimono-orta-tavuskusu',
    code: 'S2-TD-OK-M-5',
    name: 'Orta Boy Kimono',
    description: 'Tavuskuşu desenli, yeşil kenar detaylı orta boy kimono. Bel bağcıklı, rahat kesim.',
    price: 2800,
    desen: 'PAV',
    pattern: 'Tavuskuşu Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('0120'),
    images: [p('0120'), p('0127'), p('0171'), p('0197'), p('0243')],
    in_stock: true,
  },
  {
    id: 'pav-td-uk',
    slug: 'pav-kimono-uzun-tavuskusu',
    code: 'S2-TD-UK-M-5',
    name: 'Uzun Boy Kimono',
    description: 'Tavuskuşu desenli, yeşil kenar detaylı uzun boy kimono. Bel bağcıklı, akıcı silüet.',
    price: 3200,
    desen: 'PAV',
    pattern: 'Tavuskuşu Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('0279'),
    images: [p('0279'), p('0329'), p('0341'), p('0348'), p('0362')],
    in_stock: true,
  },
  {
    id: 'pav-td-st',
    slug: 'pav-gomlek-hakim-tavuskusu',
    code: 'S2-TD-ST-S/M-5',
    name: 'Hakim Yaka Gömlek',
    description: 'Tavuskuşu desenli hakim yaka gömlek. Şeftali kenar detaylı, düğmeli ön kapama.',
    price: 2400,
    desen: 'PAV',
    pattern: 'Tavuskuşu Desen',
    category: 'gomlek',
    beden: ['S/M', 'L/XL'],
    image: p('1919'),
    images: [p('1919'), p('1900')],
    in_stock: true,
  },
  {
    id: 'pav-ya-at',
    slug: 'pav-atlet-yavruagzi',
    code: 'S2-YA-AT-S/M-5',
    name: 'Atlet',
    description: 'Düz yavruağzı rengi, saten dokulu atlet. İnce askılı, V yaka.',
    price: 1200,
    desen: 'PAV',
    pattern: 'Düz Yavruağzı',
    category: 'atlet',
    beden: ['S/M', 'L/XL'],
    image: p('1559'),
    images: [p('1559'), p('1580'), p2('2128'), p('2054')],
    in_stock: true,
  },
  {
    id: 'pav-ya-sh',
    slug: 'pav-sort-yavruagzi',
    code: 'S2-YA-SH-S/M-5',
    name: 'Şort',
    description: 'Düz yavruağzı rengi, saten dokulu şort. Elastik bel, rahat kesim.',
    price: 1400,
    desen: 'PAV',
    pattern: 'Düz Yavruağzı',
    category: 'sort',
    beden: ['S/M', 'L/XL'],
    image: p2('2128'),
    images: [p2('2128'), p('1630'), p('1559'), p('1580')],
    in_stock: true,
  },
  {
    id: 'pav-ya-pt',
    slug: 'pav-pantolon-yavruagzi',
    code: 'S2-YA-PT-S/M-5',
    name: 'Pantolon',
    description: 'Düz yavruağzı rengi, saten dokulu bol paça pantolon. Elastik bel, ipli bağcık.',
    price: 1800,
    desen: 'PAV',
    pattern: 'Düz Yavruağzı',
    category: 'pantolon',
    beden: ['S/M', 'L/XL'],
    image: p('1970'),
    images: [p('1970'), p('1959'), p('1919'), p('1900')],
    in_stock: true,
  },
  {
    id: 'pav-ya-dr',
    slug: 'pav-elbise-yavruagzi-monogram',
    code: 'S2-YA-DR-S/M-5',
    name: 'Kalın Askılı V Yaka Elbise',
    description: 'Yavruağzı monogram desenli, kalın askılı V yaka elbise. Midi boy, akıcı düşüş.',
    price: 2200,
    desen: 'MONOGRAM',
    pattern: 'Yavruağzı Monogram',
    category: 'elbise',
    beden: ['S/M', 'L/XL'],
    image: p('2054'),
    images: [p('2054'), p('2099')],
    in_stock: true,
  },

  // ═══════════════════════════════════════
  // ROSEA — 8 ürün
  // ═══════════════════════════════════════

  {
    id: 'rosea-bd-cf',
    slug: 'rosea-kaftan-hakim-balikli',
    code: 'S2-BD-CF-S/M-5',
    name: 'Hakim Yaka Kaftan',
    description: 'Eteği sulu balıklı desenli, fuşya kenar detaylı hakim yaka kaftan. Uzun boy, düğmeli ön kapama.',
    price: 3600,
    desen: 'ROSEA',
    pattern: 'Eteği Sulu Balıklı Desen',
    category: 'kaftan',
    beden: ['S/M', 'L/XL'],
    image: p('1081'),
    images: [p('1081'), p('1047'), p('1102'), p('1132')],
    in_stock: true,
  },
  {
    id: 'rosea-pcd-kk',
    slug: 'rosea-kimono-kisa-pembe-cizgisel',
    code: 'S2-PCD-KK-M-5',
    name: 'Kısa Boy Kimono',
    description: 'Pembe çizgisel desenli, fuşya kenar detaylı kısa boy kimono. Bel bağcıklı.',
    price: 2600,
    desen: 'ROSEA',
    pattern: 'Pembe Çizgisel Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('0840'),
    images: [p('0840'), p('0878'), p('0892')],
    in_stock: true,
  },
  {
    id: 'rosea-pcd-uk',
    slug: 'rosea-kimono-uzun-pembe-cizgisel',
    code: 'S2-PCD-UK-M-5',
    name: 'Uzun Boy Kimono',
    description: 'Pembe çizgisel desenli, fuşya kenar detaylı uzun boy kimono. Bel bağcıklı, görkemli silüet.',
    price: 3000,
    desen: 'ROSEA',
    pattern: 'Pembe Çizgisel Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('1029'),
    images: [p('1029'), p('1034'), p('1138')],
    in_stock: true,
  },
  {
    id: 'rosea-pcd-sh',
    slug: 'rosea-sort-pembe-cizgisel',
    code: 'S2-PCD-SH-S/M-5',
    name: 'Şort',
    description: 'Pembe çizgisel desenli şort. Elastik bel, paisley baskılı kumaş.',
    price: 1600,
    desen: 'ROSEA',
    pattern: 'Pembe Çizgisel Desen',
    category: 'sort',
    beden: ['S/M', 'L/XL'],
    image: p('0780'),
    images: [p('0780'), p('0802'), p('0769')],
    in_stock: true,
  },
  {
    id: 'rosea-dp-bl',
    slug: 'rosea-bluz-duz-pembe',
    code: 'S2-DP-BL-S/M-5',
    name: 'Bluz',
    description: 'Düz fuşya pembe, saten dokulu bluz. Kayık yaka, rahat kesim.',
    price: 1400,
    desen: 'ROSEA',
    pattern: 'Düz Pembe',
    category: 'bluz',
    beden: ['S/M', 'L/XL'],
    image: p('1193'),
    images: [p('1193'), p('1197'), p('1205'), p('1258')],
    in_stock: true,
  },
  {
    id: 'rosea-dp-pt',
    slug: 'rosea-pantolon-duz-pembe',
    code: 'S2-DP-PT-S/M-5',
    name: 'Pantolon',
    description: 'Düz fuşya pembe, saten dokulu bol paça pantolon. Elastik bel.',
    price: 1800,
    desen: 'ROSEA',
    pattern: 'Düz Pembe',
    category: 'pantolon',
    beden: ['S/M', 'L/XL'],
    image: p('1258'),
    images: [p('1258'), p('1193'), p('1197'), p('1205')],
    in_stock: true,
  },
  {
    id: 'rosea-dp-at',
    slug: 'rosea-atlet-duz-pembe',
    code: 'S2-DP-AT-S/M-5',
    name: 'Atlet',
    description: 'Düz fuşya pembe, saten dokulu atlet. İnce askılı, yuvarlak yaka.',
    price: 1200,
    desen: 'ROSEA',
    pattern: 'Düz Pembe',
    category: 'atlet',
    beden: ['S/M', 'L/XL'],
    image: p('0780'),
    images: [p('0780'), p('1254'), p('0802'), p('0769')],
    in_stock: true,
  },
  {
    id: 'rosea-dp-dr',
    slug: 'rosea-elbise-duz-pembe',
    code: 'S2-DP-DR-S/M-5',
    name: 'Kalın Askılı V Yaka Elbise',
    description: 'Düz fuşya pembe, saten dokulu kalın askılı V yaka elbise. Midi boy.',
    price: 2200,
    desen: 'ROSEA',
    pattern: 'Düz Pembe',
    category: 'elbise',
    beden: ['S/M', 'L/XL'],
    image: p('1254'),
    images: [p('1254'), p2('1311')],
    in_stock: true,
  },

  // ═══════════════════════════════════════
  // VAS — 9 ürün
  // ═══════════════════════════════════════

  {
    id: 'vas-sd-kk',
    slug: 'vas-kimono-kisa-sal',
    code: 'S2-SD-KK-M-5',
    name: 'Kısa Boy Kimono',
    description: 'Şal desenli, lila kenar detaylı kısa boy kimono. Bel bağcıklı, renkli paisley baskı.',
    price: 2600,
    desen: 'VAS',
    pattern: 'Şal Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('1349'),
    images: [p('1349'), p('1365')],
    in_stock: true,
  },
  {
    id: 'vas-sd-uk',
    slug: 'vas-kimono-uzun-sal',
    code: 'S2-SD-UK-M-5',
    name: 'Uzun Boy Kimono',
    description: 'Şal desenli, lila kenar detaylı uzun boy kimono. Bel bağcıklı, görkemli akış.',
    price: 3000,
    desen: 'VAS',
    pattern: 'Şal Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('2101'),
    images: [p('2101'), p('2275'), p('2289')],
    in_stock: true,
  },
  {
    id: 'vas-sd-bl',
    slug: 'vas-bluz-sal',
    code: 'S2-SD-BL-S/M-5',
    name: 'Bluz',
    description: 'Şal desenli bluz. Asimetrik kesim, saten dokulu, renkli paisley baskı.',
    price: 1600,
    desen: 'VAS',
    pattern: 'Şal Desen',
    category: 'bluz',
    beden: ['S/M', 'L/XL'],
    image: p('1460'),
    images: [p('1460'), p('1465'), p('1520'), p('1535')],
    in_stock: true,
  },
  {
    id: 'vas-sd-sh',
    slug: 'vas-sort-sal',
    code: 'S2-SD-SH-S/M-5',
    name: 'Şort',
    description: 'Şal desenli şort. Elastik bel, renkli paisley baskılı kumaş.',
    price: 1600,
    desen: 'VAS',
    pattern: 'Şal Desen',
    category: 'sort',
    beden: ['S/M', 'L/XL'],
    image: p('1405'),
    images: [p('1405'), p('1349')],
    in_stock: true,
  },
  {
    id: 'vas-dl-bl',
    slug: 'vas-bluz-duz-lila',
    code: 'S2-DL-BL-S/M-5',
    name: 'Bluz',
    description: 'Düz lila, saten dokulu bluz. Kayık yaka, rahat kesim.',
    price: 1400,
    desen: 'VAS',
    pattern: 'Düz Lila',
    category: 'bluz',
    beden: ['S/M', 'L/XL'],
    image: p('1709'),
    images: [p('1709'), p('1713'), p('1738'), p('1852')],
    in_stock: true,
  },
  {
    id: 'vas-dl-at',
    slug: 'vas-atlet-duz-lila',
    code: 'S2-DL-AT-S/M-5',
    name: 'Atlet',
    description: 'Düz lila, saten dokulu atlet. İnce askılı, yuvarlak yaka.',
    price: 1200,
    desen: 'VAS',
    pattern: 'Düz Lila',
    category: 'atlet',
    beden: ['S/M', 'L/XL'],
    image: p('1789'),
    images: [p('1789'), p('1769')],
    in_stock: true,
  },
  {
    id: 'vas-dl-pt',
    slug: 'vas-pantolon-duz-lila',
    code: 'S2-DL-PT-S/M-5',
    name: 'Pantolon',
    description: 'Düz lila, saten dokulu bol paça pantolon. Elastik bel.',
    price: 1800,
    desen: 'VAS',
    pattern: 'Düz Lila',
    category: 'pantolon',
    beden: ['S/M', 'L/XL'],
    image: p('1738'),
    images: [p('1738'), p('1663'), p('1670'), p('1709'), p('1713')],
    in_stock: true,
  },
  {
    id: 'vas-lm-pt',
    slug: 'vas-pantolon-lila-monogram',
    code: 'S2-LM-PT-S/M-5',
    name: 'Pantolon',
    description: 'Lila monogram desenli bol paça pantolon. Elastik bel, M\'Éternelle imzalı baskı.',
    price: 2000,
    desen: 'MONOGRAM',
    pattern: 'Lila Monogram',
    category: 'pantolon',
    beden: ['S/M', 'L/XL'],
    image: p('1709'),
    images: [p('1709'), p('1713')],
    in_stock: true,
  },
  {
    id: 'vas-lm-dr',
    slug: 'vas-elbise-lila-monogram',
    code: 'S2-LM-DR-S/M-5',
    name: 'Kalın Askılı V Yaka Elbise',
    description: 'Lila monogram desenli kalın askılı V yaka elbise. Midi boy, M\'Éternelle imzalı baskı.',
    price: 2200,
    desen: 'MONOGRAM',
    pattern: 'Lila Monogram',
    category: 'elbise',
    beden: ['S/M', 'L/XL'],
    image: p('1852'),
    images: [p('1852'), p('1633'), p('1630')],
    in_stock: true,
  },

  // ═══════════════════════════════════════
  // VİRİDİS — 8 ürün
  // ═══════════════════════════════════════

  {
    id: 'viridis-bd-ok',
    slug: 'viridis-kimono-orta-balikli',
    code: 'S2-BD-OK-M-5',
    name: 'Orta Boy Kimono',
    description: 'Eteği sulu balıklı desenli, viridis yeşil kenar detaylı orta boy kimono. Bel bağcıklı.',
    price: 2800,
    desen: 'VİRİDİS',
    pattern: 'Eteği Sulu Balıklı Desen',
    category: 'kimono',
    beden: ['M'],
    image: p('0120'),
    images: [p('0120')],
    in_stock: true,
  },
  {
    id: 'viridis-ym-dr',
    slug: 'viridis-elbise-yesil-monogram',
    code: 'S2-YM-DR-S/M-5',
    name: 'Kalın Askılı V Yaka Elbise',
    description: 'Yeşil monogram desenli kalın askılı V yaka elbise. Midi boy, M\'Éternelle imzalı baskı.',
    price: 2200,
    desen: 'MONOGRAM',
    pattern: 'Yeşil Monogram',
    category: 'elbise',
    beden: ['S/M', 'L/XL'],
    image: p('0529'),
    images: [p('0529'), p('0521'), p('0604')],
    in_stock: true,
  },
  {
    id: 'viridis-ym-st',
    slug: 'viridis-gomlek-yesil-monogram',
    code: 'S2-YM-ST-S/M-5',
    name: 'Hakim Yaka Gömlek',
    description: 'Yeşil monogram desenli hakim yaka gömlek. Viridis yeşil kenar detaylı, düğmeli ön kapama.',
    price: 2400,
    desen: 'MONOGRAM',
    pattern: 'Yeşil Monogram',
    category: 'gomlek',
    beden: ['S/M', 'L/XL'],
    image: p('0378'),
    images: [p('0378'), p('0399'), p('0413'), p('0454')],
    in_stock: true,
  },
  {
    id: 'viridis-dy-bl',
    slug: 'viridis-bluz-duz-yesil',
    code: 'S2-DY-BL-S/M-5',
    name: 'Bluz',
    description: 'Düz viridis yeşil, saten dokulu bluz. Kayık yaka, rahat kesim.',
    price: 1400,
    desen: 'VİRİDİS',
    pattern: 'Düz Yeşil',
    category: 'bluz',
    beden: ['S/M', 'L/XL'],
    image: p('0639'),
    images: [p('0639'), p('0641'), p('0655'), p('0676')],
    in_stock: true,
  },
  {
    id: 'viridis-dy-pt',
    slug: 'viridis-pantolon-duz-yesil',
    code: 'S2-DY-PT-S/M-5',
    name: 'Pantolon',
    description: 'Düz viridis yeşil, saten dokulu bol paça pantolon. Elastik bel, ipli bağcık.',
    price: 1800,
    desen: 'VİRİDİS',
    pattern: 'Düz Yeşil',
    category: 'pantolon',
    beden: ['S/M', 'L/XL'],
    image: p('0639'),
    images: [p('0639'), p('0641'), p('0655'), p('0676')],
    in_stock: true,
  },
  {
    id: 'viridis-dy-at',
    slug: 'viridis-atlet-duz-yesil',
    code: 'S2-DY-AT-S/M-5',
    name: 'Atlet',
    description: 'Düz viridis yeşil, saten dokulu atlet. İnce askılı, yuvarlak yaka.',
    price: 1200,
    desen: 'VİRİDİS',
    pattern: 'Düz Yeşil',
    category: 'atlet',
    beden: ['S/M', 'L/XL'],
    image: p('0309'),
    images: [p('0309'), p('0318'), p('0641'), p('0639')],
    in_stock: true,
  },
  {
    id: 'viridis-dy-sh',
    slug: 'viridis-sort-duz-yesil',
    code: 'S2-DY-SH-S/M-5',
    name: 'Şort',
    description: 'Düz viridis yeşil, saten dokulu şort. Elastik bel, rahat kesim.',
    price: 1400,
    desen: 'VİRİDİS',
    pattern: 'Düz Yeşil',
    category: 'sort',
    beden: ['S/M', 'L/XL'],
    image: p('0309'),
    images: [p('0309'), p('0318'), p('0641'), p('0639')],
    in_stock: true,
  },
  {
    id: 'viridis-dy-dr',
    slug: 'viridis-elbise-duz-yesil',
    code: 'S2-DY-DR-S/M-5',
    name: 'Kalın Askılı V Yaka Elbise',
    description: 'Düz viridis yeşil, saten dokulu kalın askılı V yaka elbise. Midi boy.',
    price: 2200,
    desen: 'VİRİDİS',
    pattern: 'Düz Yeşil',
    category: 'elbise',
    beden: ['S/M', 'L/XL'],
    image: p('0461'),
    images: [p('0461'), p('0501'), p('0740')],
    in_stock: true,
  },
]

// ─── HELPERS ─────────────────────────────────────────────────────

export function getAllProducts(): Product[] {
  return products
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductsByDesen(desen: Product['desen']): Product[] {
  return products.filter(p => p.desen === desen)
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter(p => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  const slugs = [
    'pav-kimono-orta-tavuskusu',
    'vas-kimono-uzun-sal',
    'viridis-gomlek-yesil-monogram',
    'rosea-kaftan-hakim-balikli',
    'viridis-elbise-duz-yesil',
    'vas-elbise-lila-monogram',
  ]
  return slugs.map(slug => getProductBySlug(slug)).filter(Boolean) as Product[]
}

export const DESEN_COLORS: Record<Product['desen'], string> = {
  'PAV': '#e8956d',
  'VAS': '#b8a8c8',
  'VİRİDİS': '#1a4a3a',
  'ROSEA': '#c8356a',
  'MONOGRAM': '#2c2c2c',
}

export const DESEN_LABELS: Record<Product['desen'], string> = {
  'PAV': 'Pavo',
  'VAS': 'Vas',
  'VİRİDİS': 'Viridis',
  'ROSEA': 'Rosea',
  'MONOGRAM': 'Monogram',
}

export const CATEGORY_LABELS: Record<Product['category'], string> = {
  'kimono': 'Kimono',
  'gomlek': 'Gömlek',
  'kaftan': 'Kaftan',
  'bluz': 'Bluz',
  'atlet': 'Atlet',
  'sort': 'Şort',
  'pantolon': 'Pantolon',
  'elbise': 'Elbise',
}
